---
title: "DATA2.0"
output: pdf_document
---

```{r}
library(lubridate)
library(dplyr)
setwd("C:/Users/celinek/Desktop/Yale-NUS/NUS Data/")
DBS<-read.csv("dbs_nus_location_txn.csv")
str(DBS)
```


```{r}
library(rgdal)
Geojson<-as.data.frame(readOGR("Singapore_subdistricts.geojson"))
```

```{r}
str(Geojson)
colnames(Geojson)[4]<-"sub_zone_code"
txn<- merge(DBS,Geojson)
required_variables<-c("txn_category","day","txn_count","REGION_N")
txn<-txn[,required_variables]
txn$day<- as.POSIXct(strptime(txn$day,"%d/%m/%Y"))
#remove NA categories:
txn<-txn[complete.cases(txn),]
```

create a new dataset where counts in 7 categories are summed together
```{r}
txn_all<-aggregate(txn_count~day+REGION_N,data=txn, FUN="sum")
```

create a time series to examine the transation counts across the year
```{r}
txn_countbyday<-aggregate(txn_count~day,data=txn,FUN="sum")
txn_countbyday<-txn_countbyday[order(txn_countbyday$day),]
txn_countbyday_ts<-ts(txn_countbyday$txn_count)
library(ggplot2)
ggplot(txn_countbyday,aes(day,txn_count))+geom_line()+
  xlab("")+ylab("Daily txn")+ggtitle("Time Series Plot of DBS Daily Transaction Counts")
```
```{r}
psi<-read.csv("psi.csv")
psi<-psi[,! names(psi) %in% c("psi_three_hourly")]
txn$REGION_N <- as.character(txn$REGION_N)
#remove north-east data
txn<-txn[txn$REGION_N!= "NORTH-EAST REGION",]
txn$REGION_N[txn$REGION_N=="EAST REGION"]<-"east"
txn$REGION_N[txn$REGION_N=="NORTH REGION"]<-"north"
txn$REGION_N[txn$REGION_N=="CENTRAL REGION"]<-"central"
txn$REGION_N[txn$REGION_N=="WEST REGION"]<-"west"
```

combine the txn and psi
```{r}
psi$date <- ymd(psi$date)
txn$day<-as.Date(txn$day)
txn$day <- ymd(txn$day)
colnames(txn)[2]<-"date"
colnames(txn)[4]<-"location"
full <- left_join(txn, psi)
full<-full[complete.cases(full),]
```
```{r}
summary(full$txn_category)
full$location<-as.factor(full$location)
full<-full[,! names(full) %in% c("X")]
colnames(full)<-c("txn_category","date","txn_count","location","CO","NO2","O3","Pm10","Pm2.5","PSI","SO2")

full<-full[,!names(full) %in% c("date","location")]
```

```{r}

df <- txn_countbyday 
df$dayofweek <- wday(df$day)

df$weekend <- as.factor(ifelse(df$dayofweek == 1 & 7, 1, 0))

df %>%
  group_by(weekend) %>%
  summarize(mean_txn = mean(txn_count))

ggplot(df, aes(day, txn_count)) +
  geom_line() +
  facet_wrap(~dayofweek)
```


```{r}
txn %>%
  group_by(txn_category, date) %>%
  summarize(txn_count = sum(txn_count)) %>%
  mutate(dayofweek = wday(date)) %>%
  mutate(weekend = ifelse(dayofweek == 1 & 7, 1, 0)) %>%
  ggplot(aes(date, txn_count)) +
    geom_point(aes(col=as.factor(weekend))) +
    facet_wrap(~txn_category)
```



regression model
```{r}
n<-nrow(full)
set.seed(1)
train.indices=sample(1:n,66441)
train=full[train.indices,]
test=full[-train.indices,]

model1<-lm(txn_count~.,data=train)
model1
summary(model1)
```
```{r}
dining<-full[full$txn_category=="Dining",]
dining<-dining[,!names(dining) %in% c("txn_category")]
dining$weekend<-ifelse(dining$)

traind<-dining[train.indices,]
testd<-dining[-train.indices,]
testdX<-testd[,!names(testd) %in% c("txn_count")]

modeld<-lm(txn_count~.,data=dining)
modeld
summary(modeld)

predd<-predict(modeld,testdX)
test.rMSE<-sqrt(mean((predd-testd$txn_count)**2))


```
```{r}
library(pROC)
library(randomForest)
#m= sqrt(p)=sq(7)=2
dbscount<-randomForest(txn_count~.,data=dining,mrty=2,ntree=100,importance=TRUE,
                       do.trace=TRUE)

varImpPlot(dbscount)
```

